DROP TABLE IF EXISTS points;
CREATE TABLE IF NOT EXISTS points (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  memberId INTEGER NOT NULL,
  points INTEGER NOT NULL DEFAULT 0,
  pointsBefore INTEGER DEFAULT 0,
  pointsAfter INTEGER DEFAULT 0,
  createdAt TEXT NOT NULL DEFAULT (datetime('now'))
);

